name: Twitter Tracker
on:
  schedule:
    # Start at 8:00 AM IST daily (02:30 UTC) 
    # 23 accounts × 6sec delays = ~2 minutes total with TwitterAPI.io
    - cron: '30 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Twitter monitoring
      env:
        TWITTERAPI_IO_KEY: ${{ secrets.TWITTERAPI_IO_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        cat > config.json << EOF
        {
          "twitterapi_io_key": "$TWITTERAPI_IO_KEY",
          "gemini_api_key": "$GEMINI_API_KEY",
          "slack_webhook_url": "$SLACK_WEBHOOK_URL"
        }
        EOF
        
        # Run complete daily scan with TwitterAPI.io
        python daily_complete_scan.py
        
    - name: Commit updated state files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add daily_intelligence.json rotation_state.json user_id_cache.json || true
        git diff --staged --quiet || git commit -m "Update intelligence and rotation state [skip ci]"
        git push || true