name: Manual Test Scan (First Account Only)
on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run full scan of all accounts
      env:
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        cat > config.json << EOF
        {
          "twitter_bearer_token": "${{ secrets.TWITTER_BEARER_TOKEN }}",
          "gemini_api_key": "${{ secrets.GEMINI_API_KEY }}",
          "slack_webhook_url": "${{ secrets.SLACK_WEBHOOK_URL }}"
        }
        EOF
        
        # Run manual test scan (first account only)
        python manual_test_scan.py
        
    - name: Commit updated state files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add daily_intelligence.json rotation_state.json user_id_cache.json || true
        git diff --staged --quiet || git commit -m "Update state after manual full scan [skip ci]"
        git push || true